[package]
name = "f117a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bevy = { version = "0.12.0" }
bevy = { version = "0.12.0" , features = ["dynamic_linking"]}
#bevy_rapier3d = { version = "0.23.0", features = [ "simd-stable" ] }
bevy_rapier3d = { version = "0.23.0", features = [ "simd-stable", "debug-render-3d" ] }
lazy_static = "1.4"
bevy_third_person_camera = "0.1.7"
#bevy_prototype_debug_lines = { version = "0.11.1", features = ["3d"] }
bevy_window = "0.12.0"
bevy-scene-hook = "9.0.0"
bevy_mod_billboard = { path = "../bevy_mod_billboard" }
bevy_mod_raycast = "0.16.0"

[profile.dev.package."*"]
opt-level = 3
