[package]
name = "f117a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bevy = { version = "0.11.3" }
bevy = { version = "0.11.3" , features = ["dynamic_linking"]}
bevy-inspector-egui = "0.20.0"
bevy_editor_pls = {git = "https://github.com/jakobhellermann/bevy_editor_pls"}
bevy_rapier3d = { version = "0.22.0", features = [ "simd-stable" ] }
#bevy_rapier3d = { version = "0.22.0", features = [ "simd-stable", "debug-render-3d" ] }
lazy_static = "1.4"
bevy_atmosphere = "*"
bevy_third_person_camera = "0.1.5"
bevy_prototype_debug_lines = { version = "0.11.1", features = ["3d"] }
bevy_window = "0.11.3"

[profile.dev.package."*"]
opt-level = 3
